draw_set_font(fontText);
draw_set_color(c_black);
draw_set_halign(fa_center);
draw_set_valign(fa_middle);
draw_set_alpha(textAlpha);
draw_text(x,y,string("Enfin arrivé à la maison !"));
draw_text(x,y+25,string("Quand j’y pense, le meilleur moyen de répondre à ces personnes, c’est de grandir et de réussir ma vie."));
draw_text(x,y+50,string("Alors je vais travailler dur !"));
draw_set_font(fontTextfin);
draw_text(x,y+150,string("FIN"));
draw_set_halign(fa_left);
draw_set_font(fontText);
draw_text(x+100,+y+200,string("Par Minai et Rhagan"));
draw_set_alpha(1);