draw_set_font(fontText);
draw_set_color(c_black);
draw_set_halign(fa_center);
draw_set_valign(fa_middle);
draw_set_alpha(textAlpha);
draw_text(x,y,string("Enfin la fin des cours !"));
draw_text(x,y+25,string("J'ai eu mon bulletin trimestriel aujourd'hui : 15 de moyenne ! C'est plutôt pas mal je trouve !"));
draw_text(x,y+50,string("Enfin... ça n'a pas empêché Madame Bibine de me rappeler que je m'en sortais bien pour quelqu'un comme ''moi'' !"));
draw_text(x,y+75,string("''Quelqu'un comme moi'' ça voulait surement dire ''pour quelqu'un venant des quartiers populaires''..."));
draw_text(x,y+100,string("..."));
draw_text(x,y+125,string("Comme si c'était une obligation pour moi de tomber dans la délinquance..."));
draw_text(x,y+150,string("Je devrais ignorer ces remarques qu'on me fait tous les jours..."));
draw_text(x,y+175,string("Je dois penser à des choses positives, ça m'aidera à avancer !"));
draw_set_alpha(1);